### ISSUE TITLE
Simplify dotfile aliases

### ISSUE THREAD

**Issue by Slackadays** [seijihirao/dotfiles#1]
I was just troweling GH for all mentions of `xclip` when I found your neat dotfiles. In the `alias` section at line 15 ([link](https://github.com/seijihirao/dotfiles/blob/1d23db8757309decc4935b449fc5b5adf46df567/.config/bash/alias#L15)), there's a redundant alias for `clipboard` to go to some ugly xclip command. I wanted to suggest my project Clipboard which would let you eliminate that alias and let you copy regular files/directories as well. Also, it would save you typing since the Clipboard command `cb` is less than a quarter the length of `clipboard`. I hope my suggestion helps!

**Comment by seijihirao** [comment]
Thanks for the tip, removed with [f66dbe9](https://github.com/seijihirao/dotfiles/commit/f66dbe9cdfc965e8bfe35c20d8a8fae4db853b0e) , the alias wasn't even working anyway.

Thanks and good luck with your project!
